2022-04-11 23:43:04,891 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-11 23:43:10,956 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-11 23:48:33,506 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-11 23:51:49,138 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-11 23:51:59,606 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 17:52:56,344 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 17:55:36,381 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 17:55:38,919 ERROR: Exception on / [GET] [in /home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-04-14 17:55:45,549 ERROR: Exception on /index [GET] [in /home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-04-14 17:55:46,949 ERROR: Exception on /index [GET] [in /home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', posts=posts)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 926, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/app/templates/index.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/leandro/Documents/Leandro/Projects/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 475, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2022-04-14 17:58:37,292 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 18:00:27,512 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 18:03:46,812 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 18:08:40,707 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 18:12:11,033 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 18:16:05,717 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
2022-04-14 18:16:34,356 INFO: Microblog startup [in /home/leandro/Documents/Leandro/Projects/flask_microblog/app/__init__.py:42]
